name: Python Test Workflow

# Definindo quando o workflow será executado
on:
  push:
    branches:
      - master  # Rodar o workflow quando houver um push na branch master
  pull_request:
    branches:
      - master  # Rodar o workflow em pull requests na branch master

jobs:
  test:
    runs-on: ubuntu-latest  # Usar uma máquina virtual Ubuntu

    steps:
    # 1. Fazer o checkout do código
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurar o Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Versão do Python

    # 3. Instalar as dependências do projeto
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # 4. Rodar os testes
    - name: Run tests
      run: |
        pytest
